### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by iamfasal** [kha7iq/kc-ssh-pam#1]
I've tried this plugin to integrate our SSH server to our KeyCloak system and it works perfectly. However, we have enabled 2FA on our KeyCloak users which is must require setting in our SSO environment. 

While 2FA is ON, the ssh connectivity is not working as it comes with 401 error from the KeyCloak instance. Here is the log entry from kc-ssh-pam.log:

```
2023/09/23 14:18:37 Failed to retrieve token: HTTP request failed with status code 401
```

Anyway to make this work along with 2FA on KeyCoak setup? Any input would be helpful.

**Comment by kha7iq** [comment]
Hello @iamfasal 
This most likely is invalid credentials or the otp has expired. 
There is no Prompt for OTP when logging in, so you have to provide the password and otp on the same line by separating them with `/`
`<password>/<OTP> `

You can also test the credentials before just by calling the `kc-ssh-pam` bin

```
echo <password here>/<OTP Here >  | kc-ssh-pam
```
OR

```
echo <password here>/<OTP Here >  | /opt/kc-ssh-pam/kc-ssh-pam
```
Let me know if this solves your problem.

**Comment by iamfasal** [comment]
Thanks for the response. How can we send the OTP while SSHing to the
machine? There is no prompt showing asking for the 2FA OTP code and it just
don't accept the authentication.

Without 2FA enabled in KeyCloak user, below SSH command works fine with
KeyCloak user password.

ssh IPADDRESS -l USER

And entering KeyCloak user password to access the machine.

But with 2FA enabled for the KeyCloak user, this is not working and saying
password is incorrect. In this case, the password was correct but we can't
enter the 2FA code as there is no field asking this code while SSHing. A
prompt to enter OTP would be helpful to pass the 2FA code while SSHing.

Appreciate your help on this.

**Comment by kha7iq** [comment]
As i mentioned above there is no prompt for 2FA, this is the default behavior from the OS as we are not modifying the OS in any way. 
So when you have 2FA enabled provide the password and 2FA (OTP) on the same password prompt. 
password`/`2FA

i.e
```
mypassword/109283
```

**Comment by iamfasal** [comment]
This may be useful to someone else having same requirement. I've made a simple one-liner script to prompt for password and OTP separately and login with those here.

Requirement:

[passh](https://github.com/clarkwang/passh) 

First, compile the passh binary:
> wget https://raw.githubusercontent.com/clarkwang/passh/master/passh.c
cc -o passh passh.c
mv passh /usr/bin/

Once this is done, add the below script in to your .bashrc file:

> login-ssh() { read -p "Enter the SSH Password: " pass; read -p "Enter the OTP: " otp; passh -p "$pass/$otp" ssh IPADDRESS -l USER; }

and run 'source .bashrc' or open a new terminal. Now, you could just run login-ssh command which should prompt for the password and OTP separately and directly login to the instance if these are correct.

_Make sure to replace IPADDRESS with your actual SSH server IP, and USER with actual SSH username._

**Comment by kha7iq** [comment]
Might be useful for some one  with similar requirement . 
I am assuming original issues is resolved now, let me know.

**Comment by iamfasal** [comment]
Yes, all okay now (y)
