### ISSUE TITLE
More detailed logging information | Dockerfile to be used in a dockerized SSH server

### ISSUE THREAD

**Issue by pankalog** [kha7iq/kc-ssh-pam#15]
**Is your feature request related to a problem? Please describe.**

I am not able to get this to work using a Dockerfile that I'm trying to create. I'd like to get some more logging details out of it but I am unsure about where to find the logs. 

**Describe the solution you'd like**

somewhere where I can `cat` the logs to see what exactly has failed

**Describe alternatives you've considered**

`cat /var/log/kc-ssh-pam.log`

**Additional context**

here is the Dockerfile, maybe you can tell me if I'm doing anything wrong: 

```dockerfile

# Use Kali Linux as the base image
FROM kalilinux/kali-rolling AS base

# Avoid prompts from apt
ENV DEBIAN_FRONTEND noninteractive

# Update and install kali-linux-core and openssh-server packages
RUN apt-get update && apt-get -y install kali-linux-core openssh-server

FROM base AS ssh

# Configure the SSH server
# Create the run directory for SSH and set appropriate permissions
RUN mkdir /var/run/sshd
# Optionally allow root login via SSH; remove or modify this line if you're using a non-root user
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
# Change root password; replace 'rootpassword' with a password of your choice
RUN echo 'root:secret' | chpasswd

# Expose the SSH port
EXPOSE 22

# Start the SSH server
CMD ["/usr/sbin/sshd", "-D"]

FROM ssh AS keycloak

COPY sshd /etc/pam.d/sshd
RUN apt-get install libpam-script

COPY pam_script_auth /usr/share/libpam-script/pam_script_auth
RUN chmod +x /usr/share/libpam-script/pam_script_auth

COPY kc-ssh-pam_arm64.deb /opt/kc-ssh-pam/kc-ssh-pam_arm64.deb
RUN dpkg -i /opt/kc-ssh-pam/kc-ssh-pam_arm64.deb

COPY ./config.toml /opt/kc-ssh-pam/config.toml


CMD ["/usr/sbin/sshd", "-D"]

```

Thanks for the incredibly useful library!

**Comment by kha7iq** [comment]
Can you add a user manually in your Dockerfile which has to be same as the keycloak users, password is not important you can skip setting it all together for this user in dockerfile and then test if you are able to login with that user ?

**Comment by pankalog** [comment]
> Can you add a user manually in your Dockerfile which has to be same as the keycloak users, password is not important you can skip setting it all together for this user in dockerfile and then test if you are able to login with that user ?

Hey, I figured it out, I didn't give the config.toml the correct hostname of the Keycloak service.

@kha7iq Can I ask you though, how exactly am I supposed to set the environment variables/`kc-ssh-pam` to get it to use those environment variables? 

This is my current Dockerfile:

```dockerfile
# Use Kali Linux as the base image
FROM kalilinux/kali-rolling AS base

# Avoid prompts from apt
ENV DEBIAN_FRONTEND noninteractive

# Update and install kali-linux-core and openssh-server packages
RUN apt-get update && apt-get -y install kali-linux-core  
RUN apt-get -y install openssh-server nano curl wget
FROM base AS ssh

# Configure the SSH server
# Create the run directory for SSH and set appropriate permissions
RUN mkdir /var/run/sshd
# Optionally allow root login via SSH; remove or modify this line if you're using a non-root user
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
# Change root password; replace 'rootpassword' with a password of your choice
RUN echo 'root:secret' | chpasswd

# Expose the SSH port
EXPOSE 22

FROM ssh AS keycloak

COPY sshd /etc/pam.d/sshd
RUN apt-get install libpam-script

COPY pam_script_auth /usr/share/libpam-script/pam_script_auth
RUN chmod +x /usr/share/libpam-script/pam_script_auth

ENV KC_SSH_CONFIG=/opt/kc-ssh-pam/config.toml 
ENV KC_SSH_REALM=master 
ENV KC_SSH_ENDPOINT=http://172.22.0.4:8080/
ENV KC_SSH_CLIENTID=ssh-login 
ENV KC_SSH_CLIENTSECRET=Lbg0SmFVJUBxLNMdUaAZe4gDAINEBVod 
ENV KC_SSH_CLIENTSCOPE=openid

WORKDIR /opt/kc-ssh-pam
RUN wget https://github.com/kha7iq/kc-ssh-pam/releases/latest/download/kc-ssh-pam_arm64.deb
RUN dpkg -i /opt/kc-ssh-pam/kc-ssh-pam_arm64.deb

#COPY ./config.toml /opt/kc-ssh-pam/config.toml
#RUN /opt/kc-ssh-pam/kc-ssh-pam ${KC_SSH_CONFIG} ${KC_SSH_REALM} ${KC_SSH_ENDPOINT} ${KC_SSH_CLIENTID} ${KC_SSH_CLIENTSECRET} ${KC_SSH_CLIENTSCOPE}


CMD ["/usr/sbin/sshd", "-D"]
```

The output I get is `*** Thu Apr  4 09:50:08 2024
2024/04/04 09:50:08 Failed to retrieve provider configuration for provider https://keycloak.example.com/realms/ssh-demo with error Get "https://keycloak.example.com/realms/ssh-demo/.well-known/openid-configuration": dial tcp: lookup keycloak.example.com on 127.0.0.11:53: no such host
`
Which (I believe) are the default placeholder environment variables. If I execute `env` in the container, I can see that the environment variables are set properly. Do I need to restart the service or something?

**Comment by kha7iq** [comment]
You do not have to set the variables directly in Dockerfile, just pass them to container at run time. 
Use either config file or ENV variables , it would be much simpler this way instead of using both.
i.e 

```bash
docker run -d -e KC_SSH_REALM=master \
-e KC_SSH_ENDPOINT="http://172.22.0.4:8080" -e KC_SSH_CLIENTID=ssh-login  \
-e KC_SSH_CLIENTSECRET=Lbg0SmFVJUBxLNMdUaAZe4gDAINEBVod -e KC_SSH_CLIENTSCOPE=openid \
your-docker-image-name:latest
```

The error you get is because its using the sample config file which is added when you install kc-ssh-pam.deb. 
You can either remove the file all together or mount the file in the container when you are running it, that is if you prefer to use config file over variables. 
i.e 
```bash
docker run -d -v /home/username/config.toml:/opt/kc-ssh-pam/config.toml dockerimage:latest
```

**Comment by pankalog** [comment]
Thanks for your response,

I'm not sure I understand, I do want to set this up exclusively using environment variables, preferrably with default values in the Dockerfile for ease of use (this will be open-sourced, ideally I want people to do `docker-compose up -d` without downloading the repository). Configuring the TOML file using environment files will add a bit more confusion to the Dockerfile.

So from what I understand, I would need to install the package using dpkg, have the environment variables added, and then remove the `config.toml`? I tried that:

```dockerfile

WORKDIR /opt/kc-ssh-pam
RUN wget https://github.com/kha7iq/kc-ssh-pam/releases/latest/download/kc-ssh-pam_arm64.deb
RUN dpkg -i /opt/kc-ssh-pam/kc-ssh-pam_arm64.deb
RUN rm /opt/kc-ssh-pam/config.toml
```

But I get this output from /var/log/kc-ssh-pam.log:

```
*** Thu Apr  4 10:33:37 2024
2024/04/04 10:33:37 Error reading config file: Config File "config" Not Found in "[/opt/kc-ssh-pam / /.config]"
*** Thu Apr  4 10:33:39 2024
2024/04/04 10:33:39 Error reading config file: Config File "config" Not Found in "[/opt/kc-ssh-pam / /.config]"
*** Thu Apr  4 10:33:40 2024
2024/04/04 10:33:40 Error reading config file: Config File "config" Not Found in "[/opt/kc-ssh-pam / /.config]"
```

Once we get this resolved and I can get it reliably up and running I'd be happy to provide an example docker-compose/Dockerfile for this!

**Comment by kha7iq** [comment]
@pankalog 
I understand the problem, the config.toml file needs to exist so that env variable values can be used. But there is another issue i did not tested for docker that it is not using env variables with sshd. 

There is a simple workaround , you can generate your config with entrypoint script getting the values from env vars. 
Here is a complete example, i am not using libpam for this example and added a user `ak` 

`Dockerfile`
```bash
# Use Kali Linux as the base image
FROM kalilinux/kali-rolling

# Avoid prompts from apt
ENV DEBIAN_FRONTEND noninteractive

# Update and install kali-linux-core and openssh-server packages
RUN apt-get update && apt-get -y install kali-linux-core openssh-server nano curl wget

# Configure the SSH server
# Create the run directory for SSH and set appropriate permissions
RUN mkdir -p /var/run/sshd

RUN sed -i -e 's/^#Port 22/Port 22/' -e 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose the SSH port
EXPOSE 22

# Add the auth line to /etc/pam.d/sshd
RUN echo 'auth sufficient pam_exec.so expose_authtok log=/var/log/kc-ssh-pam.log /opt/kc-ssh-pam/kc-ssh-pam' | tee /etc/pam.d/sshd

WORKDIR /opt/kc-ssh-pam
RUN wget https://github.com/kha7iq/kc-ssh-pam/releases/latest/download/kc-ssh-pam_amd64.deb && \
    dpkg -i /opt/kc-ssh-pam/kc-ssh-pam_amd64.deb && \
    rm -rf /opt/kc-ssh-pam/kc-ssh-pam_amd64.deb

# Add the keycloak user manually 
RUN useradd ak

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```
`entrypoint.sh`
```bash
#!/bin/bash

# Define the path for the config file
CONFIG_FILE="/opt/kc-ssh-pam/config.toml"

# Check if any KEYCLOAK environment variables are set
if env | grep -q '^KEYCLOAK'; then
    echo "# Config file generated by entrypoint script" > "$CONFIG_FILE"
    echo "realm = $KEYCLOAK_REALM" >> "$CONFIG_FILE"
    echo "endpoint = $KEYCLOAK_ENDPOINT" >> "$CONFIG_FILE"
    echo "clientid = $KEYCLOAK_CLIENTID" >> "$CONFIG_FILE"
    echo "clientsecret = $KEYCLOAK_CLIENTSECRET" >> "$CONFIG_FILE"
    echo "clientscope = $KEYCLOAK_CLIENTSCOPE" >> "$CONFIG_FILE"
else
    echo "# Config file generated by entrypoint script with default values" > "$CONFIG_FILE"
    echo "realm = ssh-demo" >> "$CONFIG_FILE"
    echo "endpoint = https://keycloak.example.com" >> "$CONFIG_FILE"
    echo "clientid = keycloak-client-id" >> "$CONFIG_FILE"
    echo "clientsecret = MIKEcHObWmI3V3pF1hcSqC9KEILfLN" >> "$CONFIG_FILE"
    echo "clientscope = openid" >> "$CONFIG_FILE"
fi

echo -e "Starting SSH Server\n"

exec /usr/sbin/sshd -D
```
`docker-compose.yaml`
```yaml
version: "3.7"

# SSH Server 
services: 
  kc-ssh-pam:
    container_name: kc-ssh-pam
    image: ak/kc-ssh-pam:0.3
    environment:
      - KEYCLOAK_REALM="master" 
      - KEYCLOAK_ENDPOINT="https://keycloak.example.com"
      - KEYCLOAK_CLIENTID="linux-ssh"
      - KEYCLOAK_CLIENTSECRET="29GYExv22Prs9we8we815MqeBcxB4"
      - KEYCLOAK_CLIENTSCOPE="openid"
    ports:
      - "22:22"

```

**Comment by kha7iq** [comment]
I am going to close this as resolved, if you don't have any other question ?

**Comment by pankalog** [comment]
> I am going to close this as resolved, if you don't have any other question ?

I'm going to try this out soon, in the process I'll try to provide a Docker-compose for this. I'll either create a new issue or comment on this one. 

Thank you so much!
