### ISSUE TITLE
Users will be created even with worng password

### ISSUE THREAD

**Issue by hoshang82** [kha7iq/kc-ssh-pam#17]
first of all thank you so much, its very helpfull tool.

When we add the pam_script_auth file, and someone try with
user1@server   then enter worng password the server will create the user but access denied, in this way someone can create x-thousend users. its good if you can fix that. thank you 

Then, the script itself. In the file /usr/share/libpam-script/pam_script_auth
#!/bin/bash
adduser $PAM_USER --disabled-password --quiet --gecos ""

**Comment by kha7iq** [comment]
Hello @hoshang82 
The script is just an example and not part of module. You can modify the script in any way you like to meet your requirements. 
https://github.com/kha7iq/kc-ssh-pam/issues/18
