### ISSUE TITLE
Improve the logging

### ISSUE THREAD

**Issue by iamfasal** [kha7iq/kc-ssh-pam#9]
Any chance you could improve the logging of this module? At least, add the corresponding username to which the logins are coming in the log.

For example:
The failed attempts should log as below:

*** Sat Feb  3 13:29:42 2024
2024/02/03 13:29:42 Failed to retrieve token: HTTP request failed with status code 401 - USERNAME 

The successful attempts should log as follows:

2024/02/01 20:02:17 Token acquired and verified Successfully - USERNAME

**Comment by txj-xyz** [comment]
Will probably work on a log reformat since I started using this as well, will probably migrate to slog if possible :)

**Comment by kha7iq** [comment]
I will look into implementing this, any PRs are also welcome

**Comment by kha7iq** [comment]
Closed by https://github.com/kha7iq/kc-ssh-pam/pull/13
